public class Company{

    @AuraEnabled public String name{get;set;}
    @AuraEnabled public String phone{get;set;}
    @AuraEnabled public String address{get;set;}
    @AuraEnabled public String types{get;set;}
    @AuraEnabled public Decimal lat{get;set;}
    @AuraEnabled public Decimal lng{get;set;}
    @AuraEnabled public Decimal rating{get;set;}
    @AuraEnabled public String id{get;set;}

}
